server {
    # слушаем 80 порт
    listen 80;

    # отдаем статику
    location / {
        # (стандартный путь для статики в nginx)
        root /usr/share/nginx/html;
        # для поиска сначала просим найти файл, затем папку, 
        # затем стандартную страницу (где React Router сам сделает навигацию)
        try_files $uri $uri/ /index.html;
    }

    # все что начинается с /api - улетает в бэкенд
    location /api/ {
        proxy_pass http://backend:3000;
    }

    location /content/ {
        proxy_pass http://backend:3000;
    }
}